#include "items.h"
#include "bk.h"

items_data_t items_table[]={
    { BK_ITEM_MUSIC_NOTE        , "music notes"},
    { BK_ITEM_EGG               , "eggs"},
    { BK_ITEM_JIGGY_LEVEL       , "jiggies"},
    { BK_ITEM_RED_FEATHER       , "red feathers"},
    { BK_ITEM_GOLD_FEATHER      , "gold feathers"},
    //{ BK_ITEM_JINJO                  = 0x12, ""}, //handle differently
    { BK_ITEM_EMPTY_HONEYCOMB   , "empty honeycomb"},
    { BK_ITEM_HEALTH            , "health"},
    { BK_ITEM_HEALTH_MAX        , "health (total)"},
    { BK_ITEM_LIFE              , "lives"},
    { BK_ITEM_AIR               , "air"},
    { BK_ITEM_MUMBO_TOKEN_UNUSED, "mumbo tokens"},
    { BK_ITEM_MUMBO_TOKEN_TOTAL , "mumbo tokens (total)"},
    { BK_ITEM_JIGGY_TOTAL       , "jiggies (total)"},
    { 0, NULL},
};

items_data_t level_items_table[]={
    { BK_ITEM_BLUBBERS_GOLD     , "blubber's gold"},
    { BK_ITEM_CHIMPYS_ORANGE    , "chimpy's orange"},
    //{ BK_ITEM_VILE_SCORE_PLAYER , "player's vile score"},
    //{ BK_ITEM_VILE_SCORE_VILE   , "vile's vile score"},
    //{ BK_ITEM_GRUMBLIE          , "grumblie"},
    //{ BK_ITEM_YUMBLIE           , "yumblie"},
    { BK_ITEM_PRESENT_GREEN     , "present (green)"},
    { BK_ITEM_PRESENT_BLUE      , "present (blue)"},
    { BK_ITEM_PRESENT_RED       , "present (red)"},
    { BK_ITEM_CATEPILLAR        , "caterpillars"},
    { BK_ITEM_ACORN             , "acorns"},
    //{ BK_ITEM_TWINKLIE          , "twinklie score"},
    { BK_ITEM_JOKER_CARD        , "joker cards"},
    { 0, NULL},
};

items_data_t timer_items_table[]={
    { BK_ITEM_SKULL_HOURGLASS   , "skull hourglass"},
    { BK_ITEM_PROPELLOR_TIMER   , "propellor timer"},
    //{ BK_ITEM_CHRISTMAS_TREE_TIMER   = 0x5, ""}, //crashes game
    { BK_ITEM_HOURGLASS         , "hourglass"},
    { 0, NULL},
};



jiggy_data_t jiggy_table[]={
    /*MM*/
    { 0x01, 1, "jinjo"},
    { 0x02, 1, "ticker's tower"},
    { 0x03, 1, "mumbo's skull"},
    { 0x03, 1, "juju"},
    { 0x05, 1, "huts"},
    { 0x06, 1, "ruins"},
    { 0x07, 1, "hill"},
    { 0x08, 1, "orange switch"},
    { 0x09, 1, "chimpy"},
    { 0x0A, 1, "conga"},
    /*TTC*/
    { 0x0B, 2, "jinjo"},
    { 0x0C, 2, "lighthouse"},
    { 0x0D, 2, "alcove 1"},
    { 0x0E, 2, "alcove 2"},
    { 0x0F, 2, "pool"},
    { 0x10, 2, "sandcastle"},
    { 0x11, 2, "red x's"},
    { 0x12, 2, "nipper"},
    { 0x13, 2, "lockup"},
    { 0x14, 2, "blubber"},
    /*CC*/
    { 0x15, 3, "jinjo"},
    { 0x16, 3, "snippets"},
    { 0x17, 3, "back"},
    { 0x18, 3, "bolt"},
    { 0x19, 3, "tail"},
    { 0x1A, 3, "long pipe"},
    { 0x1B, 3, "tooth"},
    { 0x1C, 3, "rings"},
    { 0x1D, 3, "slow sawblades"},
    { 0x1E, 3, "fast sawblades"},
    /*BGS*/
    { 0x1F, 4, "jinjo"},
    { 0x20, 4, "elevated Walkway"},
    { 0x21, 4, "egg"},
    { 0x22, 4, "croctus"},
    { 0x23, 4, "mud huts"},
    { 0x24, 4, "flibbits"},
    { 0x25, 4, "maze"},
    { 0x26, 4, "tanktup"},
    { 0x27, 4, "tiptup"},
    { 0x28, 4, "mr. vile"},
    /*FP*/
    { 0x29, 5, "jinjo"},
    { 0x2A, 5, "boggy 1"},
    { 0x2B, 5, "pipe"},
    { 0x2B, 5, "boggy 3"},
    { 0x2D, 5, "snowman buttons"},
    { 0x2E, 5, "presents"},
    { 0x2F, 5, "christmas tree"},
    { 0x30, 5, "boggy 2"},
    { 0x31, 5, "sir slush"},
    { 0x32, 5, "wozza"},
    /*Lair*/
    { 0x33, 6, "first jiggy"},
    { 0x34, 6, "mumbo's mountain witch switch"},
    { 0x35, 6, "clanker's cavern witch switch"},
    { 0x36, 6, "treasure trove cove witch switch"},
    { 0x37, 6, "bubblegloop swamp witch switch"},
    { 0x38, 6, "freezeezy peak witch switch"},
    { 0x39, 6, "mad monster mansion witch switch"},
    { 0x3A, 6, "gobi's valley witch switch"},
    { 0x3B, 6, "rusty bucket bay witch switch"},
    { 0x3C, 6, "click clock wood witch switch"},
    /*GV*/
    { 0x3D, 7, "jinjo"},
    { 0x3E, 7, "grabba"},
    { 0x3F, 7, "jinxy"},
    { 0x40, 7, "matching puzzle"},
    { 0x41, 7, "maze"},
    { 0x42, 7, "water pyramid"},
    { 0x43, 7, "histup"},
    { 0x44, 7, "gobi 1"},
    { 0x45, 7, "gobi 2"},
    { 0x46, 7, "ancient ones"},
    /*CCW*/
    { 0x47, 8, "jinjo"},
    { 0x48, 8, "house"},
    { 0x49, 8, "eeyrie"},
    { 0x4A, 8, "nabnut"},
    { 0x4B, 8, "gnawty"},
    { 0x4C, 8, "zubbas"},
    { 0x4D, 8, "flower"},
    { 0x4E, 8, "summer leaf jumps"},
    { 0x4F, 8, "tree top"},
    { 0x50, 8, "top room"},
    /*RBB*/
    { 0x51, 9, "jinjo"},
    { 0x52, 9, "warehouse"},
    { 0x53, 9, "snorkel"},
    { 0x54, 9, "whistle"},
    { 0x55, 9, "funnel"},
    { 0x56, 9, "boss boom box"},
    { 0x57, 9, "propellor"},
    { 0x58, 9, "captains cabin"},
    { 0x59, 9, "crane cage"},
    { 0x5A, 9, "engine room"},
    /*MMM*/
    { 0x5B, 10, "jinjo"},
    { 0x5C, 10, "well"},
    { 0x5D, 10, "napper"},
    { 0x5E, 10, "cellar"},
    { 0x5F, 10, "church roof"},
    { 0x60, 10, "motzhand"},
    { 0x61, 10, "rain barrel"},
    { 0x62, 10, "tumblar"},
    { 0x63, 10, "flower pots"},
    { 0x64, 10, "loggo"},
    { 0, 0, NULL},
};